# Site settings
title: Resume of Alex Phelps
author:
  address:
      street: 1735 Sanctuary Dr.
      town: Owensboro Kentucky
      postcode: 42303
      country: United States
  email: alex@alexphelps.me
  name: Alex Phelps
  title: Experienced Scrum Product Owner
  twitter_username: 
  github_username:  alexphelps
  phone: +66 80 907 8180
  repository: https://github.com/alexphelps/resume
  website: http://resume.alexphelps.me
description: The resume of Alex Phelps
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://alexphelps.github.io" # the base hostname & protocol for your site

# Compress html
compress_html:
  clippings: ['!--', html, head, title, base, link, meta, style, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, hgroup, header, footer, address, p, hr, blockquote, ol, ul, li, dl, dt, dd, figure, figcaption, main, div, table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th]
  endings: [html, head, body, li, dt, dd, p, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]

# Build settings
markdown: kramdown
sass:
    style: :compressed
